# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1426454423);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1426454543);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1426454303);
user_pref("beacon.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.formfill.expire_days", 1);
user_pref("browser.formfill.saveHttpsForms", false);
user_pref("browser.history.last_page_visited", "http://www.seamonkey-project.org/releases/seamonkey2.33/");
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.startup.homepage", "https://duckduckgo.com");
user_pref("browser.startup.homepage_override.mstone", "rv:36.0");
user_pref("browser.urlbar.default.behavior", 33);
user_pref("browser.urlbar.showSearch", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "inspector%40mozilla.org:2.0.15pre,%7B59c81df5-4b7a-477b-912d-4e0fdf64e5f2%7D:0.9.91,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:2.33");
user_pref("extensions.getAddons.cache.lastUpdate", 1426454424);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.lastAppVersion", "2.33");
user_pref("extensions.lastPlatformVersion", "36.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"inspector@mozilla.org\":{\"d\":\"/home/super/.mozilla/seamonkey/6gkm053a.default/extensions/inspector@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0.15pre\",\"st\":1426454182000},\"{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}\":{\"d\":\"/home/super/.mozilla/seamonkey/6gkm053a.default/extensions/{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}.xpi\",\"e\":true,\"v\":\"0.9.91\",\"st\":1426454182000}},\"app-global\":{\"modern@themes.mozilla.org\":{\"d\":\"/usr/local/lib/seamonkey/extensions/modern@themes.mozilla.org.xpi\",\"e\":false,\"v\":\"2.33\",\"st\":1426084228000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/local/lib/seamonkey/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"2.33\",\"st\":1426084228000},\"lightning@seamonkey.mozilla.org\":{\"d\":\"/usr/local/lib/seamonkey/extensions/lightning@seamonkey.mozilla.org\",\"e\":false,\"v\":\"3.8\",\"st\":1426453868000,\"mt\":1426084299000},\"seamonkey@mozilla-enigmail.org\":{\"d\":\"/usr/local/lib/seamonkey/extensions/seamonkey@mozilla-enigmail.org\",\"e\":false,\"v\":\"1.7.2\",\"st\":1426453869000,\"mt\":1426084300000}}}");
user_pref("gecko.buildID", "20150311142351");
user_pref("gecko.mstone", "36.0.1");
user_pref("keyword.enabled", false);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("places.history.expiration.transient_current_max_pages", 26304);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.item.passwords", true);
user_pref("privacy.item.sessions", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
