# Mozilla User Preferences

/* Do not edit this file.
 *
 * This isa partial copy of the seamonkey/firefox preferences 
 * (originally from around 2014) that contains some changes
 * for better security. The file goes in the seamonkey or firefox directory.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

/* Uncomment this if you are using Tor exclusively
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.failover_timeout", 5000);

*/
user_pref("app.update.auto", false);
user_pref("beacon.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.formfill.expire_days", 1);
user_pref("browser.formfill.saveHttpsForms", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.startup.homepage", "https://duckduckgo.com");
user_pref("browser.startup.homepage_override.mstone", "rv:36.0");
user_pref("browser.urlbar.default.behavior", 33);
user_pref("browser.urlbar.showSearch", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.getAddons.cache.lastUpdate", 1426454424);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.lastAppVersion", "2.33");
user_pref("extensions.lastPlatformVersion", "36.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20150311142351");
user_pref("gecko.mstone", "36.0.1");
user_pref("keyword.enabled", false);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("places.history.expiration.transient_current_max_pages", 26304);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.item.passwords", true);
user_pref("privacy.item.sessions", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
